### ISSUE TITLE
IE 7 Bug - Nav Hidden

### ISSUE THREAD

**Issue by wihodges** [mrjasonweaver/flexnav#1]
Who would of figured there would be a bug in IE 7...

In IE 7 on page load - the navigation is mysteriously hidden. After resizing of the window, the navigation appears. 
Finally figured out that IE7 does not like [role="navigation"].

The solution: replaced the custom selector, [role="navigation"], with class .rolenavigation in html, css, & js. and it fixed the issue.

**Comment by mrjasonweaver** [comment]
Thanks! Let me know when the site you're working on goes live. I'd love to see real uses of this in the wild.
