### ISSUE TITLE
Drop-down arrow seems a little redundant on no-touch devices

### ISSUE THREAD

**Issue by nternetinspired** [mrjasonweaver/flexnav#10]
First up, thanks for the awesome plugin. 

Second, apologies for not putting this in a pull request but I have made quite a few changes to make this Joomla compatible and so I'm more than a little out of sync with you now. If I was more competent in Git I could probably get round that, but I'm not!

Anywho, one of the changes I made which you may find useful is that I reset li.item-with-ul back to 100%, at larger viewports, on devices that do not support touch, as these operate via :hover anyway. So, I have the drop-down arrow only on touch enabled devices. 

I did this as I feel that it adds possible confusion for .no-touch users, to whom it isn't apparent what the relevance of the arrow is when :hover triggers a drop-down. 

Hope I've made sense. Thanks again for all the code :)

Seth

**Comment by mrjasonweaver** [comment]
Hmm, good point about the arrow on non-touch interfaces. I'm going to start making some major changes to the plugin (adding support for more than 2 levels) and I'll def consider this. Thanks!

**Comment by alexander-sibert** [comment]
The plugin is very great. I will convert it for my Drupal 7 Page http://www.neofelis.de with Omega Theme. Have you tested it on all Internet Browsers and mobile Operating systems?

**Comment by mrjasonweaver** [comment]
@alexander-sibert 

Adding the plugin and css is a good starting point for any responsive web project but you should note a few things:

Because IE8 and below doesn't understand media queries, you'd need to serve a stylesheet for ie8 and below using conditional comments.

Add this below your main stylesheet and the flexnav.css if that is in a separate file:

`
`

And in the ie8-and-down.css add your styles for large viewports. So everything in the media query in flexnav.css would go in here:

```
`p {font-size: 100%; margin-bottom: 1.5em; line-height: 1.25em;}    
.flexNav-touch [role='navigation'],
.flexNav-no-touch [role='navigation'] {
    display: block; 
}
.menu-button {
    display: none;
}
[role='navigation'] li {
    position: relative;
    list-style: none;
    float: left;
    display: block; 
    background-color: #333; 
    width: 20%;     
}
.flexNav-no-touch .item-with-ul:hover > ul { 
    opacity: 1;
    top: 3.1em; 
    position: absolute; 
}   
[role='navigation'] li a {
    border-left: 1px solid #000;
    border-bottom: none;        
}
.flexNav-no-touch [role='navigation'] li ul {
    position: absolute; 
    top: auto;
    left: 0;
    opacity: 0;
    visibility: hidden;
    height: 1px;
    z-index: 1;         
}
[role='navigation'] li ul li a {
    border-bottom: none;    
}   
.flexNav-touch [role='navigation'] li ul.sub-menu {
    position: absolute; 
    top: auto;
    left: 0;
    display: none;
    z-index: 1;                 
}   

.flexNav-no-touch .item-with-ul:hover > ul   { 
    visibility: visible;
    opacity: 1;
    height: auto;
    display: block; 
    border-right: 1px solid #000;
    border-bottom: 1px solid #000;      
}
```

`

It wouldn't be responsive for IE8 and below but you don't necessarily need it to be for those browsers. 

Make sense?
