### ISSUE TITLE
Automatic z-index

### ISSUE THREAD

**Issue by mors3** [mrjasonweaver/flexnav#100]
Personally I think the navigation should be the highest stacked item on the screen, but I've implemented flexnav along with a jquery slider (bxslider) in a responsive template (Responsify) and the slider is taking height precedence.

Would be a nice feature if the z-index of the navigation was automatically assigned top height on page load?

**Comment by mrjasonweaver** [comment]
@mors3 I see what you're saying but what would I set it to? `z-index: 999;` Then someone is bound to have an element set higher than that on their page. I'll look into it but my initial reaction is not to mess with it.

**Comment by mrjasonweaver** [comment]
@mors3 Also, feel free to send a pull request!

**Comment by mors3** [comment]
Hi, thanks for that, dug around the code to see if I could work out where it was failing as the built in z-indexes actually looked ok, tried implementing in the same level as the slider and it worked fine (the flexnav is implemented in header and the slider is implemented into a div outside the header, later in the document).

So I'll close this and work out what in all hell I'm doing wrong and if I can wire in something tasty to resolve this nicely I'll fire off a pull request! :)

**Comment by kakubei** [comment]
I'm having the same issue with slippry carousel and cannot get the dropdown navigation to show up above the slippry carousel. Which class do I need to increase the z-index for? It would seem that `.flexnav` should do it but t doesn't work for some reason.

**Comment by elevationstudio** [comment]
The problem with the z-index is -webkit-transform-style: preserve-3d - take that out and the dropdown menus appear in front of the carousel.
