### ISSUE TITLE
Dropdown Stuck in "Open" Position outside Hover

### ISSUE THREAD

**Issue by silverdragon686** [mrjasonweaver/flexnav#104]
I noticed that the dropdown menu will stick in the "open" position when you move the mouse away from the menu. It then will close when you hover back. This happens in IE, Firefox and Chrome. I'm not sure if this is a jQuery/JavaScript issue or something with the CSS (I did a bunch of modifications and I don't know if I messed up the code beyond recognition).

I also noticed that the dropdown will stay behind z-index elements in Chrome, despite setting the menu elements to z-index: 999. The other element are only z-index: 1, and appear normal in IE and Firefox.

**Comment by silverdragon686** [comment]
I fixed the Chrome z-index issue. I just added "position: relative; z-index: 999" to the .flexnav class and it works now.

I should note above, that once the menu is stuck open, it closes when you hover over the top menu link; in other words, it's backwards from how it should work.

**Comment by mrjasonweaver** [comment]
Not sure about your specific code but can't reproduce at: http://jasonweaver.name/lab/flexiblenavigation/
