### ISSUE TITLE
Is the ZIP messed up?

### ISSUE THREAD

**Issue by TonyScialdone** [mrjasonweaver/flexnav#105]
I'd love to implement this...it looks awesome! I downloaded and unzipped the ZIP, and opened index.html to see it in action on my computer. The top-level menus are all "open" for index.html, and don't show subs. I didn't change anything...just unzipped and opened in these browsers, on Windows 8.1:

Chrome 31.0.1650.63 m
Safari for Windows 5.1.7 (7534.57.2)
IE 11.0.9600.16438
Firefox 25

Am I being dense, and missing something obvious?

![fn](https://f.cloud.github.com/assets/6164622/1728080/8134d9d0-62a8-11e3-816e-5eb67d53004e.jpg)

**Comment by mrjasonweaver** [comment]
You have to run a local server to get the jQuery linked to CDN. I just run a python server and specify a port in a terminal shell:

``` bash
> python -m SimpleHTTPServer 8900
```

Otherwise link up to jQuery source locally.
