### ISSUE TITLE
Internet Explorer 9 - Menus Expand/Contract Unpredictably

### ISSUE THREAD

**Issue by FishLord** [mrjasonweaver/flexnav#108]
Using IE9, there seems to be a problem, even on the demo page, with the menus either not expanding on mouseover or not contracting on mouseout.

The screenshot linked below shows an example. This is a shot from my browser, with Javascript enabled. Each menu did not contract when I moved on to a different menu item.

[Imgur](http://i.imgur.com/SUVoNO1.jpg)

**Comment by tomByrer** [comment]
Have an issue of menus not contracting in Win7 Firefox 24 on rare random occasion as well, exactly as FishLord's image demonstrates.
I am unable to replicate.

**Comment by kirkofalltrades** [comment]
I can confirm IE9 is having issues.  Loaded up my Virtual PC w/ IE9 and seeing the same issues with both my site and on the demo page.  When hovering over a main menu item with children, the menu starts full expanded and then retracts.  Moving the mouse cursor outside the menu causes the li with children to appear again.  Hovering over the parent again seems to reset it correctly.  Move mouse outside and hover again and the cycle repeats.

Thanks,
Kirk

**Comment by mrjasonweaver** [comment]
Try using HoverIntent. Some have reported that fixes the issue.

**Comment by FishLord** [comment]
indyplanets - please could you expand on your suggestion or link to relevant discussion?

**Comment by mrjasonweaver** [comment]
jQuery HoverIntent Plugin: http://cherne.net/brian/resources/jquery.hoverIntent.html
HoverIntent Options: https://github.com/indyplanets/flexnav#options

**Comment by kirkofalltrades** [comment]
I just wanted to comment back and say that using HoverIntent did solve my issues.

Thank you for your support!

**Comment by mrjasonweaver** [comment]
@kirkofalltrades Great! Glad it worked out.
