### ISSUE TITLE
A couple of possible changes?

### ISSUE THREAD

**Issue by jimlakey** [mrjasonweaver/flexnav#11]
I was excited to find your plugin as it did almost everything I wanted for a responsive navigation, so thank you for your work. And for sharing it of course...

I tweaked it a little to fit my needs and I thought I's share what I did incase it is of any interest. I [forked your repo here](http://github.com/jimlakey/flexnav) and put a version up [here](http://applecanyondesigns.com/lab/flexNav/) to test on devices.

In a nutshell, here's what I did and why:
- Made the arrows disclose on hover or click for clearer UI.
- Added a default class of .flexNav-no-js which is replaced by either touch or no-touch class if JS working in browser. Added .flexNav prefix so it didn't clash if modernizr is used, but isn't reliant on it either. Added this in order to:
  - Make plugin function more fully if JS disabled
  - Allow for hover states to work on wider viewports if JS disabled
- Found bug when going from wide viewport to small - then opening and closing the menu and submenus - then going back to wide, that the jquery toggle injects `display:none`, and then the submenus don't appear on hover or click. Used `.css({'display':''});` to reset css to defaults on resize.

I also changed a few things unnecessarily, such as the viewport meta tag and removing the footer css as I was prepping it for my project. I didn't initiate a pull request as I probably changed too much code to suit my own tastes and maybe deviated too far from the original plugin?

Also, as a disclaimer, I am in the process of learning javascript and jquery so most of the changes I introduced seem to work but may not be a great way of doing things.

**Comment by mrjasonweaver** [comment]
@jimlakey Thanks for this! I'm in the process of making FlexNav a bit more robust and have ideas for several themes. I want to separate the css into a lean base file and have several options to add on themed css. 

Also, currently the plugin doesn't work with more than two levels of menus. I'd like to build in this feature.

That means flexnav.js will need to go through a major overhaul and I should be working on a major release over the next few weeks or so.

**Comment by jimlakey** [comment]
Actually... Something I recently added seems to have screwed things up on mobile devices. Let me check it out...

**(Just read above comment)** Great - good to know. Look forward to seeing the new version.

**update** Turns out ems didn't work as a breakpoint in the jquery file. Above files working again on mobile as far as I can see.
