### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by artguycreative** [mrjasonweaver/flexnav#111]
I cannot get the drop downs to work properly, not even when coping and pasting source code from the FlexNav site into a new document. I've spent hours diagnosing the issue, but without a solution. The drop downs remain visible, and the responsive menu does not reveal the drop downs. It is clearly an issue on my end, but I am at a loss to determine the issue.
![screen shot 2014-01-06 at 4 29 25 pm](https://f.cloud.github.com/assets/6334623/1855251/a974f9d4-772a-11e3-872c-da7405e8bd24.png)

**Comment by mrjasonweaver** [comment]
Any errors in the inspector? Do you have jQuery referenced?

**Comment by artguycreative** [comment]
No errors, and I referenced jQuery (jquery-1.10.2.min.js) every way I know how. I know it's not much to go off of.

**Comment by artguycreative** [comment]
OK, I think I lied. Inspector revealed the following:
    .   Uncaught ReferenceError: jQuery is not defined       jquery.flexnav.js:14
    .   Uncaught TypeError: Object [object Object] has no method 'flexNav'        index_test.html:111

**Comment by artguycreative** [comment]
http://www.artguycreative.com/matthaiSite/index_test.html

**Comment by mrjasonweaver** [comment]
You have jQuery called after jquery.flexnav.js. Needs to be before. See [usage](https://github.com/indyplanets/flexnav#usage).

**Comment by artguycreative** [comment]
You are my hero, good sir. Still, I am learning.

**Comment by artguycreative** [comment]
You are my hero, good sir. Still, I am learning.
