### ISSUE TITLE
Why is this so slow?

### ISSUE THREAD

**Issue by marcinciarka** [mrjasonweaver/flexnav#112]
On the video 17s - see? Every such plugin is slow and choppy...

**Comment by marcinciarka** [comment]
Well done, denial.

**Comment by mrjasonweaver** [comment]
Your question made no sense to me. I thought it was spam. Can you elaborate?

**Comment by marcinciarka** [comment]
Im using Galaxy Nexus with 4.4 android, Chrome 31 (mobile) and this (and many others out there) plugin is working great on desktop, but it's really choppy on mobile. Check out your video - http://jasonweaver.name/lab/flexiblenavigation/
on 17 second you will see the menu slide down when tapped. It's really bad :< (on iPad!)

I'm not a developer, but i've read that this may be caused by animating height (jQuery slideDown) which is not hardware accelerated. Nevertheless, even Bootstrap mobile nav menu is working choppy on every device I had in my hands.

I'm looking for a mobile navigation that is simple to use and provide smooth app-like experience.
I didn't want to sound harsh, sorry.
