### ISSUE TITLE
Submenu first slides down then it slides to the right

### ISSUE THREAD

**Issue by sethstha** [mrjasonweaver/flexnav#115]
i was trying to fix the width of submenu in dropdown and when i did it, it worked but with some little problem. the problem was that first it's slides down and then it slides to the right to increase the width of submenu. is it possible to overcome this problem. i want my menu to slide down without sliding to the right after sliding down however i think there is problem with css. it might be first taking width of whole list item and then of submenu. any help will be appreciated.
Thank you

**Comment by mrjasonweaver** [comment]
Hi @sanjeev18 - Yeah, you just have to play around with the css. The css is just a starter for devs/designers. It's meant to be changed to fit your specific project. Think of the css as a starting point that you change to fit your design.

**Comment by sethstha** [comment]
i almost changed everything but menu still not works same problem with the new issue. you can have a demo look over here

http://www.artguycreative.com/matthaiSite/

**Comment by cr4ckm3** [comment]
@sanjeev18 Answer is in your question.
Set .flexnav .sophInvest > ul { width: 110% } and remove .flexnav li.sophInvest ul li {
width: 110%;
}

**Comment by sethstha** [comment]
thanks it worked like charm
