### ISSUE TITLE
Demo Not working

### ISSUE THREAD

**Issue by CydGoblin** [mrjasonweaver/flexnav#123]
i downloaded the zip but when i open it is not working, any ideas?
i've tested in safari and chrome

**Comment by mrjasonweaver** [comment]
Demo has to be on a server to hit the jQuery CDN. You can run a simple python server in Terminal or throw it on your local dev env.

```
cd flexnav
python -m SimpleHTTPServer
```

Else, link your local copy to a local version of jQuery.
