### ISSUE TITLE
Hovering Issue

### ISSUE THREAD

**Issue by ninadingole** [mrjasonweaver/flexnav#128]
On full screen the menus when a menu is hovered it closes other open menus but if the window is resized and then if menu is hovered other open menus are not closed all shows at same time and then menu start behaving in weird way
![Weird Behavior](https://f.cloud.github.com/assets/1947050/2255120/099ea1b8-9dee-11e3-9f26-73323cdbf55e.png)

**Comment by LandingOnJupiter** [comment]
There's a solution for this under issue #119 .
