### ISSUE TITLE
How to remove triangle in menu button?

### ISSUE THREAD

**Issue by kakubei** [mrjasonweaver/flexnav#129]
Hello, thanks for Flexnav, it seems great. However I can't figure out how to remove the triangle from the menu button which triggers the drop down. I have my own style so that .menu-button is not even called, yet the triangle still appears. I suspect it is added via Javascript? 

Anyway, how can I remove it?

Thanks

Update: I removed it by using:

```
.navicon { display: none; }
```

In the class I'm using for the button. Just wondering if this is the best way or is there another suggested?

Many thanks.

**Comment by PeterKnightDigital** [comment]
I think it's the JS file. 
I notice on lline 105 it mentions
 `<i class="navicon">&#9660;</i>`

Thats the little triangle.

**Comment by kakubei** [comment]
Thanks eladnova, I solved it with the above edit so as not to mess with the JS file :)
