### ISSUE TITLE
Bug on Windows 8?

### ISSUE THREAD

**Issue by wintnerdzn** [mrjasonweaver/flexnav#14]
Just saw a weird bug on a Vaio Duo running on Windows 8. Touching the "Menu" button, the menu briefly appears then disappears...does not stay open so user can select an option.

**Comment by mrjasonweaver** [comment]
I'll need to find a Win8 phone to test. Thanks.

**Comment by wintnerdzn** [comment]
This was on a Sony Vaio Duo Tablet, Jason. I went to a Sony store to test. Haven't really been able to find a Win 8 phone to test as the MS store blocks access to all sites. Windows 8 didn't always show this bug on other tablets and laptops I tried. Ugh. The range of devices we have to serve is mindboggling.

**Comment by mrjasonweaver** [comment]
@wintnerdzn Is this still an issue?

**Comment by wintnerdzn** [comment]
I haven't had a chance to retest. Will try to get to it asap.

**Comment by noatak** [comment]
It is the same issue with the desktop version of ie9 and ie10  browser. When you resize the browser window to "mobile" size. If you click a menu item the subitems appear and then disappear again.
This happens only if you click the menu item for the first time. The second time it works as expected.

**Comment by mrjasonweaver** [comment]
@noatak Thanks for the report. Working on a fix for this.

**Comment by tomsyver** [comment]
Can confirm the same behaviour on WIn7/IE9. Another issue on latest Chrome is a little graphical glitch if you click the expand area of a menu item (Not just hovering, but actually clicking it). This happens only in desktop view. Great work on the menu by the way..

**Comment by bluehatdesign** [comment]
I'm seeing this same behavior on an Asus TF700 tablet Android version 4.1.1 and a Nexus 4 phone Android version 4.2.2 with the default browser. The menus work correctly on Chrome on these same devices.

**Comment by mokargas** [comment]
Also confirmed on a Nexus 4, Android 4.2.2, inside the Android Webview. As bluehatdesign mentions, it works in the now default Chrome browser, but not in the Webview client.

**Comment by mrjasonweaver** [comment]
With version 1.0 release: https://github.com/indyplanets/flexnav/pull/56 - This will be fixed.
