### ISSUE TITLE
Horizontal Navigation don't fits at same line not responsive enough with more than 5 parent li in first ul

### ISSUE THREAD

**Issue by RetinaInc** [mrjasonweaver/flexnav#140]
![flexnavproblem](https://cloud.githubusercontent.com/assets/3315212/2576995/a60c5446-b978-11e3-98c2-803ac03b5e93.jpg)

Horizontal Navigation don't fits at same line(not responsive enough) with more than 5 parent li in first ul

**Comment by mrjasonweaver** [comment]
You can set the `calcItemWidths` option to "true" to dynamically calculate the percentages of each item: https://github.com/indyplanets/flexnav#options

**Comment by RetinaInc** [comment]
ah great. I think its better set that to true as default.
