### ISSUE TITLE
Hover makes menu flash

### ISSUE THREAD

**Issue by seanriceaz** [mrjasonweaver/flexnav#146]
When my mouse rolls quickly over a menu with a dropdown (and exits), it flashes visible and then hides quickly. Consider implementing a timeout on hover exiting--maybe a css transition to make this feel less jarring.

I know it's just responding (and quickly!) to my mouse hovering... 

(Chrome Version 35.0.1916.114 on OSX)

**Comment by jdabs** [comment]
You might want to try looking at the fixes in #119  . I got the issue fixed today after following the first suggestion for changing the js on line 102.

**Comment by mrjasonweaver** [comment]
@seanriceaz You can use FlexNav with HoverIntent: https://github.com/indyplanets/flexnav#options
