### ISSUE TITLE
No Arrow/Menu won't open on mobile browsers

### ISSUE THREAD

**Issue by ghost** [mrjasonweaver/flexnav#147]
I have integrated flexnav into a site for a client, and all seemed well on desktop, but on iPhone/Android Browsers, there is no arrow showing to open the menu, and clicking the menu does nothing.

If I request the desktop version of the site, everything looks exactly the same, but the arrow shows and the menu works. I am at a loss for what to do.

https://www.productionproducts.net/ppi-store 

Note - I am using a breakpoint of 1024px, and I am using a different menu solution above 1024px, but that is all working fine via media queries. I have also removed the other menu completely in testing, to ensure the other menu solution isnt causing any issue.

So you will only see the flexnav on a width <=1024px. All is well on the desktop browsers, but not the mobile

**Comment by mrjasonweaver** [comment]
Hmm, I'm sorry you're having this problem. Looks like a bug in your code but I'm unable to assess the problem. It's working fine at the demo site: http://jasonweaver.name/lab/flexiblenavigation/
