### ISSUE TITLE
Click problem

### ISSUE THREAD

**Issue by mnuhlicek** [mrjasonweaver/flexnav#15]
Hello,

when I d middle click, to open in new tab the menu dissapears. Also when I have href="#".

Thank you

**Comment by mrjasonweaver** [comment]
Wow, that's weird. I'm wondering what it could be. I'll take a look. Thanks for filing the bug.

**Comment by mrjasonweaver** [comment]
I think I've managed to fix this. Tested here: http://jasonweaver.name/lab/flexiblenavigation/

Not sure what was causing that. Pushed some minor updates and after couldn't replicate the issue. Let me know if you have any more problems with it. Thanks!

**Comment by melster777** [comment]
Hi indyplanets the issue was still there i visit the page http://jasonweaver.name/lab/flexiblenavigation/ when you resize ur browser and click the second level it not showing instead its closing...

**Comment by mrjasonweaver** [comment]
Ok, thanks. Working on this.

**Comment by melster777** [comment]
Thanks indyplanets. 

This is better than bootstrap. hopefully it can be fix. and also this can handle up to what level of sub menu?

**Comment by mrjasonweaver** [comment]
Thanks, and yes it will.

-Jason

**Comment by mrjasonweaver** [comment]
@melster777 I've updated the plugin and fixed the submenu click bug on small screens. Still more fixes and features to come!

**Comment by melster777** [comment]
thanks inyplanets this is awesome!
