### ISSUE TITLE
Click vs. mouse over

### ISSUE THREAD

**Issue by mnuhlicek** [mrjasonweaver/flexnav#16]
Hello, I found new issue. When you click for roll-out, roll-in then mouseover roll-outs doesn't work until refresh.

**Comment by mrjasonweaver** [comment]
I'm trying to iron this issue out. Will be a fix for this in the next few iterations. Thanks!

**Comment by mrjasonweaver** [comment]
@mnuhlicek Hi there. This bug has been fixed in the latest release. Closing this issue.

**Comment by mrjasonweaver** [comment]
I've reverted the code on this issue. I'm rethinking my approach for adding in extra hover events via js Reopening.

**Comment by mrjasonweaver** [comment]
This bug has been fixed: v.0.4.5
