### ISSUE TITLE
Flex Nav Sub Menus Not Hiding

### ISSUE THREAD

**Issue by tcertain** [mrjasonweaver/flexnav#161]
Flex Nav Sub Menus not hiding when page is opened for first time, on any device

**Comment by bethan** [comment]
Have you solved this issue? 
I'm having the same problem. When unzip the folder from github, and look at the demo files then all menu items are displayed. Also no arrows are shown.

**Comment by mrjasonweaver** [comment]
You have to have the files on a local server or change jquery to call a local version.

**Comment by tcertain** [comment]
Umm, your own demo shows the nav as not hiding in latest FF on Windows7

Tena

**Comment by tcertain** [comment]
@bethan - no it has not been fixed, just got the reply via indyplanets. Obviously indyplanets has not opened the zip and tried it, because they closed the issue on me.
![flexnav](https://cloud.githubusercontent.com/assets/8310335/3815709/e134836a-1cc7-11e4-8d4e-3e8b67993347.jpg)

**Comment by mrjasonweaver** [comment]
@tcertain Your first comment said nothing about FF. The demo here: http://jasonweaver.name/lab/flexiblenavigation/ works fine for all devices I have to test on. 

Since the call to jQuery is trying to hit a CDN you'll need to throw the files in an area on your local machine that's served by a local web server. I use python for a simple web server: python -m SimpleHTTPServer. Or you can change the call to jQuery to a local version.

**Comment by mrjasonweaver** [comment]
@bethan You can change this line: https://github.com/indyplanets/flexnav/blob/master/index.html#L185 in index.html to a local path to a local version of jQuery that you've downloaded. I promise it'll work after that.

**Comment by mrjasonweaver** [comment]
@tcertain https://github.com/indyplanets/flexnav/issues/161#issuecomment-51232835 is the snarkiest comment I've ever gotten from someone using my **free** software.

**Comment by tcertain** [comment]
Very frustrating to download something and it not work as is, free or paid for. Was not trying to be "snarky". Sorry for the inconvenience. I see that it does work after you put a copy of jquery inside the unzipped file folder and change the source code in the index.html file to read 

<script src="jquery.js"></script>
