### ISSUE TITLE
Navigation is not working

### ISSUE THREAD

**Issue by alkie** [mrjasonweaver/flexnav#165]
i don't know what is the problem because i'm a newbie when it comes to js and github 
when i tried to test what you upload in github. it doesn't work
can someone please tell me what is the problem
thanks
![capture](https://cloud.githubusercontent.com/assets/9126279/4587359/9f6ed336-502a-11e4-8b62-629495521f44.JPG)

**Comment by mrjasonweaver** [comment]
@bozz2 See https://github.com/indyplanets/flexnav/issues/161
