### ISSUE TITLE
flexnav still flashing dropdowns on page change

### ISSUE THREAD

**Issue by myrna** [mrjasonweaver/flexnav#176]
I checked #64 but this solution didn't work for me; I'm not using SASS, just plain old CSS and JS on a WordPress site, with the most current version of flexnav, 1.3.3.  At every page change on a full-width desktop browser all the dropdown menus flash open, then close. I would really love to use flexnav because of its mobile behavior with dropdowns, but the flash looks awful. If there is no known fix can anyone recommend another responsive dropdown menu that works in a similar fashion?  Thank you!

**Comment by mrjasonweaver** [comment]
You can edit the css to get the desired effect you're looking for.

**Comment by myrna** [comment]
Hmmm... well, I am going through the CSS line by line (flexnav.css) and still no luck.  Any pointers in the right direction would be greatly appreciated.
