### ISSUE TITLE
Dropdowns for All Devices Not Working in Chrome Once on a Server

### ISSUE THREAD

**Issue by ghost** [mrjasonweaver/flexnav#18]
The downloaded file works fine on my local computer, but once I upload it to a server it stops functioning completely.

**Comment by AblazeRich** [comment]
Did you upload the whole lot? All the supporting files? Sorry if that seems patronising, but I've missed things like this in the past myself

**Comment by mrjasonweaver** [comment]
Sorry, I haven't had a chance to update it. Will try this week if I get time.

**Comment by mrjasonweaver** [comment]
@kaseysnider Can you link me to it? Might be able to debug for you as it should work. Works here: http://jasonweaver.name/lab/flexiblenavigation/

**Comment by AblazeRich** [comment]
Thanks man.
Here's my link:
http://www.mason-uk.co.uk/responsive/html5boilerplate5.html

**Comment by mrjasonweaver** [comment]
@AblazeRich Sorry, I think you might be posting in the wrong thread. I haven't updated this plugin to support older ie browsers.

**Comment by AblazeRich** [comment]
Whoops!

**Comment by ghost** [comment]
@indyplanets Thanks for your help, we will have this link live for a few days and then it will be taken down:
https://www.strsoh.org/Demo/index.html

**Comment by mrjasonweaver** [comment]
@kaseysnider Looks like you need to add jQuery to the page. It's not loading it from the cdn for some reason. So just upload jQuery to your server and reference it in the document before flexnav.js.
