### ISSUE TITLE
Multiple Menu Options

### ISSUE THREAD

**Issue by JasonHoffmann** [mrjasonweaver/flexnav#2]
Hello, 
I am running into difficulties floating one menu-button div next to another once the menu is collapsed. In other words, two dropdown menus side by side. I would like to put a search dropdown next to the main menu. I will be working on this but please let me know if you have any suggestions.

**Comment by mrjasonweaver** [comment]
Can you post a link to the code?

**Comment by JasonHoffmann** [comment]
I'm just first trying to conceptualize how this would work. Ultimately I would hope it could look something like www.bostonglobe.com with multiple menu options in compact mode. But I am having trouble figuring out to how to change the js for this.

I put together a really banal jsfiddle with really just some tweaked css. http://jsfiddle.net/jhoffm34/3UL7W/

**Comment by mrjasonweaver** [comment]
You're trying to float two elements side-by-side? You'd have to adjust the width of the elements so the total width of the two floated elements were less than or equal to 100%.
