### ISSUE TITLE
Why is it not possible to use an ID/class instead of [role='navigation'] ? 

### ISSUE THREAD

**Issue by karok** [mrjasonweaver/flexnav#20]
I started to use flexnav, I like it but it's not easy to work with it. 

Why isn't it possible to use a class/ID name instead of role="navigation" in the script : 
    $("[role='navigation']").flexNav();

it doesn't it work if i use:    $("#nav").flexNav();  ??  

I tried everything but can't work it out? 

Another issue - the submenus of my menu are directly open and not like in your example closed when you open the menu. I'm not sure why not. 
The website is not online right now, but I can send you with PN the site+logininfo. 

Thanks
Karo

**Comment by mrjasonweaver** [comment]
You can use an id for your menu if you like. Probably a bug on your particular page that's causing issues.
