### ISSUE TITLE
WordPress Appointkart plugin issue in iphone device

### ISSUE THREAD

**Issue by ghost** [mrjasonweaver/flexnav#206]
When plugin page load then by default open calendar , So how I hide the by default open calendar. [See the image](https://i.stack.imgur.com/5O5zk.jpg) in Iphone page load calander open. website link : [website link](http://demo.samaxxpreview.com/)

**Comment by mrjasonweaver** [comment]
@savan13 That's not part of the flexnav codebase, right?

**Comment by ghost** [comment]
@indyplanets  ok
so how can i post this questions ?
