### ISSUE TITLE
2 FlexNavs on one site

### ISSUE THREAD

**Issue by karok** [mrjasonweaver/flexnav#21]
If I'm using 2 Flex Navs on one site - 
one effects the other (when opening one for example - the other closes) 
How to fix that?

**Comment by mrjasonweaver** [comment]
FlexNav isn't really built to accomodate two navs on a page. It's really just meant to be a global navigation.

**Comment by karok** [comment]
i did some changes in the script and doubled it up - so now it works! I can publish it later, but I'm having an issue right now that on desktop it works perfectly (just a page with one flexnav) but on mobile not (it seems the script doesn't start working)- and I'm having a testingpage with the same code and there it works. I'm getting crazy here =)))

**Comment by jrsinclair** [comment]
I've created a small modification that would make having multiple menus possible. See https://github.com/indyplanets/flexnav/pull/44
