### ISSUE TITLE
Menu closes when user scrolls on small screens

### ISSUE THREAD

**Issue by mrjasonweaver** [mrjasonweaver/flexnav#23]
A bug if a user is on a small screen, opens the mobile menu and scrolls, the menu closes. This because (I suspect) the window resize event fires and as a result, closes the menu.

**Comment by mrjasonweaver** [comment]
Only confirmed bug result on Android 2.3 default browser

**Comment by petercarsater** [comment]
I have the same problem on iOS 6.1 (iPhone). If I open the mobile menu, click to open level two (it opens) and then scroll, the menu closes.

**Comment by mrjasonweaver** [comment]
Thanks. I'll look into fixing this tonight.

**Comment by mrjasonweaver** [comment]
This bug has been fixed with v.0.4.8 release. Toggling class `.show` with css transitions to hide/show menu instead of using `.hide()` and `.show()`
