### ISSUE TITLE
EM values?

### ISSUE THREAD

**Issue by jfroom** [mrjasonweaver/flexnav#25]
How can data-breakpoint work with EM values? Thanks.
http://blog.cloudfour.com/the-ems-have-it-proportional-media-queries-ftw/

**Comment by mrjasonweaver** [comment]
HI @jfroom, I'm working on adding this. Thanks.

**Comment by jfroom** [comment]
Oh sweet. I found a handful of JS -> EM functions, but it seems the trick there is knowing when the user has zoomed in or out in their browser. Not sure if polling on an interval is necessary. Hmm.

**Comment by mrjasonweaver** [comment]
Added support for em units in FlexNav v.0.4.9
Use `<ul class="flexnav" data-breakpoint-em="50"> <li>...</li> </ul>`
