### ISSUE TITLE
Close FlexNav Menu on click/touch selection

### ISSUE THREAD

**Issue by wintnerdzn** [mrjasonweaver/flexnav#26]
Trying to upgrade my site to FlexNav.js 0.4.6 and the new code doesn't close the menu when user selects a list item. The menu on your demo (http://jasonweaver.name/lab/flexiblenavigation/single-page-pattern.html#page) stays open too.

Can we please put this back (as an option)?

**Comment by mrjasonweaver** [comment]
I'll add that in this evening. Thanks.

**Comment by mrjasonweaver** [comment]
Added this in FlexNav v.0.4.7

See it in action here: http://jasonweaver.name/lab/flexiblenavigation/single-page-pattern.html

**Comment by mrjasonweaver** [comment]
BTW, you'll need to add a `.one-page` class to the `<body>`, `.menu-button`, and FlexNav `<ul>`

**Comment by wintnerdzn** [comment]
Thanks Jason. It's not working for me (testing locally). I added the .one-page class to the HTML but not sure if and where I need to add .one-page to my CSS (my site is quite different from your demo which makes this quite confusing).

The menu-button works fine...toggling open/close.

**Comment by wintnerdzn** [comment]
Jason, just checked your demo on Android 2.3.4 and the menu doesn't stay fixed when select an item li

**Comment by mrjasonweaver** [comment]
The older Android os needs `user-scalable=no` in the viewport meta tag. I've updated my demo with this change. http://jasonweaver.name/lab/flexiblenavigation/single-page-pattern.html
