### ISSUE TITLE
Allow for changable navicon

### ISSUE THREAD

**Issue by spirelli** [mrjasonweaver/flexnav#27]
First of all, great work on this. I'm not an expert, not have I got much chance on testing on various devices, bit this seems down-to-earth, usable and straight-forward to implement.

What I cannot see being part of this is a changeable navicon, where the icon is different if the sub-menu is visible compared to when it's not. Particularly in the mobile navigation it would be useful to display an icon that suggest that an item can be collapsed by clicking on it again. E.g. I'd like to use a + icon for expandable items and a – sign for collapsible items. I cannot see that it's currently possible to do that with CSS.

Would be great if this could be considered for the next version.

**Comment by mrjasonweaver** [comment]
This is definitely a feature I'm working on.

**Comment by ghost** [comment]
+1 - first just give touch-button an active-class if its parent li is open like this:  "touch-button active".

**Comment by mrjasonweaver** [comment]
@kkutschera `active` class for touch-button has been pushed for v1 release: https://github.com/indyplanets/flexnav/pull/56

@spirelli I'm going to create a group of demos. One of which will show changing the navicon and touch-buttons with css. Will post back here when I push those demos out. Thanks!
