### ISSUE TITLE
Progressive enhancement on mobile devices

### ISSUE THREAD

**Issue by LimeBlast** [mrjasonweaver/flexnav#28]
I love this, and will probably use it on a few of my upcoming projects - but unless I'm mistaken, it doesn't seem to work on mobile sites with javascript disabled.

If you're above the breakpoint (i.e. on a desktop) with no javascript, the fallback CSS still allows access to all of the pages within the menu...

... but if you're below the breakpoint (i.e. on a mobile), you're unable to do anything except see a block that says 'menu', but are unable to interact with it in anyway.

Now I realise that this probably covers a very small subset of people, but surely for these people, it would be better to just show all the links available, rather than hide them behind a button that doesn't do anything?

**Comment by mrjasonweaver** [comment]
Thanks @LimeBlast - you are correct. I'll progressively enhance FlexNav for small screens this weekend.

**Comment by LimeBlast** [comment]
Cheers :)

One other thing I've noticed - I have an android tablet (10" running 4.1.1) and it doesn't work correctly on there. I try tapping the arrows to open the sub menus, etc.. and the submenu will appear for half a second, then vanish again.

It works correctly on my iPad.

Thank you again :)

**Comment by mrjasonweaver** [comment]
@LimeBlast Hmm, That's interesting. Thank you for reporting that. I'll do some testing this weekend.

**Comment by mrjasonweaver** [comment]
@LimeBlast I've pushed some updates for this. Nav is open by default with no js for small screens. 

Also think I've managed to fix the bug on large Android tablets. Can you confirm?

Thanks!

**Comment by LimeBlast** [comment]
I'm happy to confirm that both issues are fixed - thank you :)
