### ISSUE TITLE
Close flexnav on click/touch?

### ISSUE THREAD

**Issue by JoshHehn** [mrjasonweaver/flexnav#3]
Is it possible to include an option to close the flexnav toggle when an item is clicked/touched? I'm using flexnav on a single, long-scrolling page and this would be very useful because I'm not sending users to different pages and the flexnav currently stays open.

**Comment by mrjasonweaver** [comment]
Hmm, haven't thought about using it that way. I'll certainly see about making this the default.

**Comment by mrjasonweaver** [comment]
Updated to close menu when an item is clicked/touched by default.
