### ISSUE TITLE
Sub nav items not dropping in IE8

### ISSUE THREAD

**Issue by mrjasonweaver** [mrjasonweaver/flexnav#33]
Regression bug.

**Comment by mrjasonweaver** [comment]
I believe this has been fixed with the release of v0.7

**Comment by chrisbohnsack** [comment]
Hi, Flexnav is great! Except that this comment appears to be correct -drop menus not working on IE8 (as much as I hate IE)

**Comment by OxyFuse** [comment]
Just verified that the issue still exists in v0.7
