### ISSUE TITLE
Menu button for mobile

### ISSUE THREAD

**Issue by abrahamspaa** [mrjasonweaver/flexnav#34]
Whether it is possible to remove menu button for mobile alone?

I.e: For mobile need only the item's list to be visible directly not the menu button.

**Comment by mrjasonweaver** [comment]
I'll see about adding this at the next milestone.

**Comment by mrjasonweaver** [comment]
For the next version on FlexNav (https://github.com/indyplanets/flexnav/pull/56) you could easily edit the css to achieve this. 

If editing flexnav.scss (SCSS) change:

```
  &.with-js {
    max-height: 0;
  }
```

to

```
  &.with-js {
    max-height: auto;
  }
```

If editing flexnav.css change

```
.flexnav.with-js {
    max-height: 0; }
```

to

```
.flexnav.with-js {
    max-height: auto; }
```

and add `display: none` to `.menu-button` to hide the menu button for either scss or regular css

You can download FlexNav release candidate v1.0 at https://github.com/indyplanets/flexnav/releases/tag/v1.0-rc1
