### ISSUE TITLE
v.0.7 bug: sub ul menu doesn't s slide up when mouse moves quickly

### ISSUE THREAD

**Issue by gudh** [mrjasonweaver/flexnav#35]
![snip20130504_1](https://f.cloud.github.com/assets/3378031/462166/0e4ba632-b480-11e2-886d-dee38924811a.png)

**Comment by mrjasonweaver** [comment]
Thanks for reporting this. I'm pushing a fix in v.0.08.

**Comment by digitalcraftco** [comment]
You may have already fixed this but I modified the animation function with .stop(true, true) to remove queued animation and complete the current animation immediately:

return $('.item-with-ul').on('mouseenter', function() {
          return $(this).find('>ul').addClass('show').stop(true, true).slideDown(settings.animationSpeed);
        }).on('mouseleave', function() {
          return $(this).find('>ul').removeClass('show').stop(true, true).hide();
        });

Seems to have fixed the sticky sub-menus when moving mouse to fast but haven't fully tested it out.

**Comment by mrjasonweaver** [comment]
@digitalcraftco Nice! Thanks for this. I'm working on releasing v0.8 this week. I'll roll this into the build.

**Comment by digitalcraftco** [comment]
Awesome looking forward to it. Thanks for spearheading this script. Should be very useful for future projects.

**Comment by mrjasonweaver** [comment]
Added in. Closing this issue.
