### ISSUE TITLE
Sub menus stay open on resize

### ISSUE THREAD

**Issue by digitalcraftco** [mrjasonweaver/flexnav#36]
If I open up the subnav when browser is shrunk down the dropdowns stay open when I enlarge the browser back to large break point.

I wonder if it needs a close all submenus in the window.resize function. If => breakpoint?

This worked: $('.item-with-ul ul').hide();

 else {
        $nav.removeClass("sm-screen").addClass("lg-screen");
        $nav.removeClass('show');
        $('.item-with-ul ul').hide();

**Comment by mrjasonweaver** [comment]
Hey @digitalcraftco — Sorry for the delayed response. I believe this is a regression bug that broke that functionality in v0.7. I'm currently working on v0.8 release that should fix this.

**Comment by mrjasonweaver** [comment]
Closing this. Was fixed in v0.8
