### ISSUE TITLE
Option for site logo button to be visible when in small screen mode

### ISSUE THREAD

**Issue by dheian** [mrjasonweaver/flexnav#37]
I love this plugin! Is there a suggested way (or could you include it as an option in the css) to have a, say, 50px wide button to display a site logo/home button on the same line as the small screen menu?

i.e.

| Logo | Menu Button __________|

It'd be a great way to still show the site's branding while making more small screen real estate available for content. I tried doing it myself but when I tried inline-block'ing the logo and flexnax, the drop down choices were squashed. I got this:

| Logo | Menu Button __________|
_____ | drop down nav choice ___| 

instead of this:

| Logo | Menu Button __________|
| drop down nav choice_________|

**Comment by mrjasonweaver** [comment]
@dheian Hmm, you could use a css background image technique to accomplish this. Not sure I'd make this a feature for the plugin as it seems a little out of scope.
