### ISSUE TITLE
how to resize the flexnav to fit many anchors inline?

### ISSUE THREAD

**Issue by moonzy** [mrjasonweaver/flexnav#38]
Hi,

First of all thank you very much for sharing this awesome menu.

then, i have a menu with several links on the root level so i want to know how can i resize the flexnav to fit in the same line.

Any help is welcome thanks!!!!

**Comment by mrjasonweaver** [comment]
You want to divide the number of top level items by 100%. That will give you the width in % to set each item in the css. Find `.flexnav li` and change `width: 20%`. It's set to 20% by default to accomodate 5 items.
