### ISSUE TITLE
Small delays for easier navigation (drop down menus)

### ISSUE THREAD

**Issue by NinaG** [mrjasonweaver/flexnav#39]
Could you please add some little delays so that it's easier to navigate the dropdown-menu?

Most people don't move very exact with the computer mouse from one submenu level to the next sub-level. The submenu often closes in that situation because for a milisecond they hit space outside of the menu.
If you close the submenu-levels only after a small delay, this would not happen and make a much better user experience.

It would also look smoother if the submenus roll out/in with a little transition effect.

**Comment by mrjasonweaver** [comment]
Hi @NinaG - Yes, this is something I'm working on for the next release. Thanks for your input!

**Comment by NinaG** [comment]
Do you know when you're going to publish the next release? :)

**Comment by mrjasonweaver** [comment]
I'm super busy right now but I'll try to release this weekend. Thanks for your patience.

**Comment by NinaG** [comment]
Wonderful :)

Are you also taking paid projects? Maybe I can get customers to pay for new features.

**Comment by mrjasonweaver** [comment]
@NinaG Can you email me? indyplanets@gmail.com

**Comment by NinaG** [comment]
Sure

**Comment by mrjasonweaver** [comment]
I have a major release coming that will allow flexnav and hoverIntent to play nice: https://github.com/indyplanets/flexnav/pull/56

Release version 1.0 is scheduled for Monday 8/5
