### ISSUE TITLE
Navmenu disappears on click

### ISSUE THREAD

**Issue by Paul-Morris** [mrjasonweaver/flexnav#4]
I think this is intentional but I don't understand why? The code is designed to hide the whole meny on click but this seems very jarring to the eye when it is deployed to a working site. Is it necessary, because when I commented it out the nav still seems to work fine?

<code>
        // Closes nav menu after links clicked/touched
        $this.find('a').click(function() {
            $this.hide();
        });
</code>

Nice work though! I am testing it on a site now. I'd like to implement a nav similar to starbucks.com

**Comment by mrjasonweaver** [comment]
Yeah, I added that to be used on a single page site with the links anchoring to an id further down the page. It was a feature request. Might make it an option instead.

**Comment by mrjasonweaver** [comment]
Here's that feature request: https://github.com/indyplanets/flexnav/issues/3

**Comment by Paul-Morris** [comment]
Thanks! I understand now
