### ISSUE TITLE
doesn't work in noConflict mode

### ISSUE THREAD

**Issue by milo3k** [mrjasonweaver/flexnav#40]
Please see [http://wordpress.stackexchange.com/questions/101021/using-flexnav-with-wordpress](http://wordpress.stackexchange.com/questions/101021/using-flexnav-with-wordpress)

**Comment by mrjasonweaver** [comment]
There is a fork that adds support for noConflict: https://github.com/pallandt/flexnav

I'm adding this to FlexNav in the next major release.

**Comment by mrjasonweaver** [comment]
Support for noConflict is merged in version 1.0 Release: https://github.com/indyplanets/flexnav/pull/56
