### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by danny-englander** [mrjasonweaver/flexnav#41]
I love this plugin and I've integrated it into a Drupal theme I'm developing. I'm wondering if you would consider changing the license to "Unlicensed" - http://unlicense.org/  

Personally the WTFPL license does not bother me but I think it could potentially offend some potential users and the link that it goes to. I think essentially 'Unlicensed' achieves the same thing as WTFPL.  Thanks!

**Comment by mrjasonweaver** [comment]
This is a good idea. I'll change it.

Thanks,
-Jason

**Comment by danny-englander** [comment]
Thanks Jason!

**Comment by mrjasonweaver** [comment]
License has been changed in v0.8: https://github.com/indyplanets/flexnav/pull/42
