### ISSUE TITLE
Submenus won't open in IE8

### ISSUE THREAD

**Issue by OxyFuse** [mrjasonweaver/flexnav#45]
v0.7 and the latest v0.8 can't open submenus in IE8

**Comment by mrjasonweaver** [comment]
@OxyFuse Looking into it. thanks.

**Comment by paulcredmond** [comment]
I can also verify this. I made a quick workaround for the minute:

```
    <!--[if lt IE 9]>
        <script>
        $(document).ready(function() {
            $('span.touch-button').click(function() {
                $('ul.sm-screen').toggle();
            });
        });
        </script>
    <![endif]-->
```

**Comment by ac-bristol** [comment]
Any news on this bug?

**Comment by mrjasonweaver** [comment]
Just pushed a fixed for this. Would love some testers to make sure it's working properly.

**Comment by leanda** [comment]
Still having an issue in IE8, can't open the Menu Button.

Script error Line 62 'console' is undefined.

**Comment by mrjasonweaver** [comment]
@leanda Can you clarify re 'Menu Button'? Shouldn't be a menu button in IE8. Only supports large screen layouts for IE 8.

**Comment by leanda** [comment]
Could that be because I'm using respond.js?
