### ISSUE TITLE
Swipe Gestures/Scroll on iOS

### ISSUE THREAD

**Issue by ghost** [mrjasonweaver/flexnav#47]
Great plugin; finding it very useful for quick mobile nav implementation.

I've noticed that if a user taps on the nav but intends to swipe/scroll rather than toggle expansion on an iOS device (test iPhone 5 on iOS 6), scroll will be disabled, and the nav will expand regardless of the users finger position.  

I'm not sure how to interpret this from my relatively novice jQuery grounding; the code seems to be looking for such behavior (the touchmove/mousemove block).

**Comment by mrjasonweaver** [comment]
Working on better touch implementation for the next major release.

**Comment by mrjasonweaver** [comment]
For version 1.0: https://github.com/indyplanets/flexnav/pull/56 I'm using a different touch/click event implementation but it's still a little tricky to get this to work properly. I want to get rid of the 300ms delay on most webkit mobile browsers but that means using `touchstart` and `click` in the same event. This results in firing if a user happens to swipe across the tap target. For me, I'd like to keep it the way it is for now. I'll think about a better solution for the next release.
