### ISSUE TITLE
Problem with sub-lists on last navigation point

### ISSUE THREAD

**Issue by NinaG** [mrjasonweaver/flexnav#50]
At the moment all sub-lists open to the right side, which usually works nice EXCEPT for the last navigation point. As soon as the visitor of the website clicks on the last navigation point of each level, the sub-lists open too far on the right side of the browser-window and create a horizontal browser-scrollbar.

You can see this issue on your demo-website if you put two sub-level-lists to the last navigation point.
![demo](https://f.cloud.github.com/assets/1219952/769387/5894f5dc-e8b4-11e2-8aa1-df74f8068c6a.jpg)

A solution for this would be, that you change the CSS code so that sub-lists (only!) on the last navigation point open to the left-side instead of the right-side.

**Comment by mrjasonweaver** [comment]
Thank you for this, Nina. I wouldn't want to change the css, however, because it works fine for wider viewports. I would rather keep the css as small and simple as possible while allowing anyone to edit the css to fit their particular case.
