### ISSUE TITLE
Menu button is not clickable on IE9

### ISSUE THREAD

**Issue by rizqinizamil** [mrjasonweaver/flexnav#51]
I just tested my web on IE9, but menu button is not clickable on it. So nav menu cannot be shown. It also happened on your flexnav site.

Is there any solution for it?

Many thanks,
Rizqi

**Comment by katdef** [comment]
Same issue when testing IE9 on desktop, but found that it works after I hit F12 (open developer tools) and continues to work after that even if I close developer tools.

**Comment by mrjasonweaver** [comment]
Tested new version 1.0 release here: http://jasonweaver.name/lab/flexiblenavigation-test/

For https://github.com/indyplanets/flexnav/pull/56 I've changed the way I use click/touch events and may have fixed this issue. Tested using browserstack.
