### ISSUE TITLE
Changing the direction of displayed submenu

### ISSUE THREAD

**Issue by aryoxp** [mrjasonweaver/flexnav#52]
Is there a way to change the displaying direction of submenu (i.e. to the left) when submenu is overflowed to the right of browser window? So if I have a menu on the rightmost of browser window, its submenu will be shown to the left side of parent menu rather than showing on the right side of its parent as configured by default.

Thanks

**Comment by mrjasonweaver** [comment]
Considering adding this in the next release. Otherwise you'd need to write some css. :)

**Comment by mrjasonweaver** [comment]
Closing this issue for now. I'll come back and link to an example for you. :smiley_cat:
