### ISSUE TITLE
3rd level dropdowns?

### ISSUE THREAD

**Issue by anointed** [mrjasonweaver/flexnav#6]
I've been working on trying to tweak the flexnav to work with sub-sub-navigation on mobile devices.

I have run into one problem with the js that I just can't solve.

demo:
http://jsfiddle.net/wphotline/DqZgb/13/

If you click uncategorized, then click group forums, notice the group forums is collapsing inward instead of opening up?

The menu works great when only having 1 level, but has issues on the second.

Can you help fix this?

**Comment by mrjasonweaver** [comment]
Hmm, you're using the old non-plugin code for the demo you've linked to. Not sure the new version would work with 3rd level drop downs either, though. I'll do some hacking over the next few days and get back with you.

**Comment by anointed** [comment]
that would be great. Yeah, I didn't even know there was a new vs. until this morning. I've been hacking around with the old vs. for weeks now trying to get the 3rd level working. I know it's possible, just my js chops aren't that advanced yet, but getting closer.

**Comment by mrjasonweaver** [comment]
Hey @anointed - I'm still working on this. I need to rethink how the whole nav is implemented in order to allow for multiple levels of drops. I've got some major overhauling to do so it'll be a while before the next version release.

**Comment by anointed** [comment]
Awesome. 
I'm actually glad to hear that it's not a quick n easy project as I tried it for almost a week before crying out for help. Turns out it was a difficult project for a newbie to cut his jQuery teeth on, oh well

**Comment by ds4web** [comment]
Hi! Is there any solution for multiple layer Navigation using either the older code or the plugins ?

**Comment by alexander-sibert** [comment]
You find also nice responsive Navigations with the zurb foundation framework: http://foundation.zurb.com/docs/navigation.php

**Comment by ds4web** [comment]
The link worked for me. Thanks a lot.

**Comment by mrjasonweaver** [comment]
I've started to add support for multi-level sub menus. Tested here: http://jasonweaver.name/lab/flexiblenavigation/

I'm slowly rolling in some new features and making the plugin overall a little more robust. Closing this issue.
