### ISSUE TITLE
Don't open flex-nav mobile menu on page load

### ISSUE THREAD

**Issue by ryanjkoehler** [mrjasonweaver/flexnav#60]
On page load on iPad and iPhone, the mobile menu is open then collapses.  Can we set it to be closed by default on page load?

**Comment by mrjasonweaver** [comment]
@ryanjkoehler I've coded FlexNav to show the menu by default just in case the user doesn't have javascript. I may rethink this approach in a future release but for now you can add a tiny bit of js and css to get the desired outcome:

Add this to the `<head>` of your web page so it executes before the rest of the page loads.

```
    <script type="text/javascript">
        var doc = document.getElementsByTagName('html')[0];
        doc.setAttribute('class', 'flexnav-js');
        window.setTimeout(doc.setAttribute('class', 'flexnav-set'), 1000);
    </script>

```

Add this to the top of your flexnav css:

```
html.flexnav-js .flexnav {
  opacity: 0;
}
html.flexnav-js.flexnav-set .flexnav {
  opacity: 1;
}
```

All this does is change the opacity of the flexnav `ul` to 0, then waits a second and changes it back to 1. Feel free to adjust that `1000` in  `setTimeout` to more or less. 1000 is 1 sec.

**Comment by prowebdesignro** [comment]
Hi. First of all, thanx for this cool code!

Secondly. Unfortunately, the suggested fix doesn't work. What works is loading jQuery in the <head> (Flexnav JS can be left in the end of the page).

If I load jQuery in the end of the document, I get the subs flash for a second behavior EVERYWHERE: desktop, iPad, Androids (HTC phone, Samsung Galaxy tablet). It would be great if the bug would be eliminated from the core code alltogether.

**Comment by prowebdesignro** [comment]
UPD. Loading jQuery in head eliminated bug on desktops, but not on iPad.

**Comment by prowebdesignro** [comment]
ok, sorry for spamming here:). I think I found a quick fix for this bug without the need to move JS around in the html document.

In CSS file  - part for mobile devices - :
1. remove .flexnav.opacity {
   opacity: 0; }
   //line 18-19
2. add .flexnav{ display:none;}
3. add display:none into .flexnav li ul {
   width: 100%; }
   // line 43-44

Then into the media querie part (for larger screens) -:
1. add display:block to .flexnav {  
   overflow: visible; 
   position:relative;}
   //line 110- 112

hope I didn't forget anything:)

**Comment by mrjasonweaver** [comment]
@prowebdesignro FlexNav is coded to hide the menu only if js is enabled. So by default the menu would show if the user doesn't have JavaScript. If you don't care about accessibility without js then this solution will work fine.

**Comment by bradweaver** [comment]
Can you guys help me understand @prowebdesignro 's suggestion? I've tried doing this exactly as you have it and all it does is hide the menu. I think step 2 is wrong here, why would I set flexnav to display none and then not have a way to turn that back off. I'm using sass. this is a HUGE problem for us, it's flashing everytime on every page load. The native, raw version of your code with no modifications is doing it as well on three different installs we're working with. We're running the latest version, downloading it right from here.

**Comment by mrjasonweaver** [comment]
@bradweaver You could take my advice here: https://github.com/indyplanets/flexnav/issues/60#issuecomment-22584607 or load jquery and flexnav.js in the head of your document.

**Comment by ryanjkoehler** [comment]
For #60 I needed a function wrapper around the first parameter of the setTimeout function for it to work.
