### ISSUE TITLE
Switch from small screen menu to wide screen menu

### ISSUE THREAD

**Issue by Swebmaster** [mrjasonweaver/flexnav#62]
Hi,

Using your Demo http://jasonweaver.name/lab/flexiblenavigation/
When I start using the menu for small screen (open and close sub-menu without  clicking links) and switch back to wide screen, the menu doesn't work as excepted. 
Tested on Safari 6.0.5 and Firefox 22.0.

Thank you,

**Comment by Swebmaster** [comment]
This Drupal theme (http://gratis.themehuis.com) is using flexnav and the bug describe doesn't appear. Anyone have an explanation?

**Comment by OxyFuse** [comment]
Is this the same as #36?

#36 is still present in v1.1.

**Comment by Swebmaster** [comment]
indyplanets fix and close that issue #36. So I'm not sure it's the same but it looks similar.

**Comment by mrjasonweaver** [comment]
There is currently a valid issue here where hover support is borked when going through to small screen back to large screen and clicking around a bit on small screen nav. Looking to fix this soon.

**Comment by mrjasonweaver** [comment]
This has been fixed in v1.3: https://github.com/indyplanets/flexnav/releases/tag/v1.3
