### ISSUE TITLE
Breakpoint not wroking

### ISSUE THREAD

**Issue by OxyFuse** [mrjasonweaver/flexnav#63]
I have tested changing the breakpoint to 640 or 480 but it always change the menu at 800.

I have tried both `data-breakpoint-em="30"` and `data-breakpoint="480"` and it's not working.

**Comment by mrjasonweaver** [comment]
Hi @OxyFuse. Did you also change the media query in the css? The breakpoint data attribute is for loading classes via js. You still have to use media queries to make layout changes.

**Comment by OxyFuse** [comment]
Ahh I see, I thought everything is automatic :D

**Comment by ryanjkoehler** [comment]
I was confused by this too, thinking the same way as @OxyFuse

**Comment by jbonigomes** [comment]
+1
