### ISSUE TITLE
Flashing on load

### ISSUE THREAD

**Issue by bradweaver** [mrjasonweaver/flexnav#64]
Sorry if this is a common fix, but the menu always "flashes" open when you first load the page on any device. It looks terrible. Is there any way for it not to load the submenu on load and only show the top level items on desktop and the menu button on mobile?

Thanks for the great framework though, this is great.

**Comment by mrjasonweaver** [comment]
I'm considering changing this but for now take a look at https://github.com/indyplanets/flexnav/issues/60

**Comment by mrjasonweaver** [comment]
@bradweaver The easiest way to get the "flash" to stop on small screens is to delete this in flexnav.scss:

```
  &.with-js {
    max-height: 0;
  }
```

and put that 'max-height: 0;' in the .flexnav block above it. That way the height of the of the nav is 0 on page load.

**Comment by mrjasonweaver** [comment]
@bradweaver I've pushed out a new release for this. https://github.com/indyplanets/flexnav/releases/tag/v1.1.1 I need to figure out a better way to achieve this but for now this will get rid of the "flash".

**Comment by bradweaver** [comment]
Hi Jason, thanks so much for the quick help. Was it a single selector that was changed in this release or multiple items? Just trying to avoid having to redo all of my custom CSS for the colors, icon, etc. if possible. If not I can run it through Kaleidoscope. Thanks again.

FYI, the other fix you suggested did work for small screens.

**Comment by mrjasonweaver** [comment]
@bradweaver https://github.com/indyplanets/flexnav/issues/64#issuecomment-22917522 should do the trick and is what I changed in the new release.

**Comment by bradweaver** [comment]
Thanks, but it's not working for me. This is what I have in the initial section at the top of the sass file:

.flexnav {
    -webkit-transition: none;
  -moz-transition: none;
  -ms-transition: none;
  transition: none;
    -webkit-transform-style: preserve-3d; // stop webkit flicker
  overflow: hidden;
    margin: 0 auto;
    padding-top:10px;
    width: 100%;
    position:relative;
    z-index:99999;
    max-height: 0;

  &.with-js {
    opacity: 0;
  }

  &.opacity {
    opacity: 0;
  }

```
&.show {
    max-height: 2000px;
opacity: 1;
    -webkit-transition: all .5s ease-in-out;
-moz-transition: all .5s ease-in-out;
-ms-transition: all .5s ease-in-out;
transition: all .5s ease-in-out;
background-color: #34495e;
}
&.one-page {
    position: fixed;
    top: 50px;
    right: 5%;
    max-width: 200px;
}
```

**Comment by mrjasonweaver** [comment]
@bradweaver remove:

```
&.with-js {
opacity: 0;
}
```

Might need to clear browser cache. Tested here: http://jasonweaver.name/lab/flexiblenavigation/ and works for me.

**Comment by bradweaver** [comment]
Hi Jason, well, we tried a completely clean install of your code in Drupal and it doesn't work. The absolute raw version of the minified js and the scss file from your folder in 1.1 was installed and it still flashes in all browsers on all devices with absolutely no modifications. Cleared incognito or clear browser caches, cleared CMS cache, and inspected code showing exactly the same scss as your file are not working. it flashes every time on every device. It looks really bad, no idea what to do.

**Comment by mrjasonweaver** [comment]
Does it flash at http://jasonweaver.name/lab/flexiblenavigation ?

**Comment by bradweaver** [comment]
It doesn't. I'm sure it's me, just trying to understand what it is. Our top level flexnav section is identical to the one in the zip and we're using the minified js file directly from the zip:

.flexnav {
    -webkit-transition: none;
  -moz-transition: none;
  -ms-transition: none;
  transition: none;
    -webkit-transform-style: preserve-3d; // stop webkit flicker
  overflow: hidden;
    margin: 0 auto;
    padding-top:10px;
    width: 100%;
    position:relative;
    z-index:99999;
    max-height: 0;

  &.opacity {
    opacity: 0;
  }

```
&.show {
    max-height: 2000px;
opacity: 1;
    -webkit-transition: all .5s ease-in-out;
-moz-transition: all .5s ease-in-out;
-ms-transition: all .5s ease-in-out;
transition: all .5s ease-in-out;
background-color: #34495e;
}
&.one-page {
    position: fixed;
    top: 50px;
    right: 5%;
    max-width: 200px;
}
```

**Comment by christianhanvey** [comment]
I simply changed the display value of the submenus.
The JS will re-enable the submenus, but users without JS (and everyone while the page is loading) will not see the submenus flash. 

```
.flexnav li > ul {
//  display: block;
  display: none;
}
```

**Comment by bradweaver** [comment]
Thanks Christian, that worked!
