### ISSUE TITLE
Not really a bug, but it'll be nice to have.

### ISSUE THREAD

**Issue by 1JS** [mrjasonweaver/flexnav#65]
![snip20130820_2](https://f.cloud.github.com/assets/5161842/990879/98963e0a-0945-11e3-8a09-a5b6386dea68.png)

I click the Nav (<= breakpoint), when I enlarge the window width, it'll be nice to reset the Nav instead of showing multiple dropdowns

**Comment by mrjasonweaver** [comment]
@1JS Thanks. Yes, this is something I'm working on concurrent with issue https://github.com/indyplanets/flexnav/issues/62
