### ISSUE TITLE
Delay for closing the submenu on mouse out

### ISSUE THREAD

**Issue by Swebmaster** [mrjasonweaver/flexnav#66]
It would be nice to control the delay for closing the submenu on mouse out. 
Thank you!

**Comment by mrjasonweaver** [comment]
@Swebmaster FlexNav has support for adding the jQuery plugin HoverIntent: http://cherne.net/brian/resources/jquery.hoverIntent.html

I'm in the process of creating a demo to show this but for now that that should get you started. Check out the options for FlexNav: https://github.com/indyplanets/flexnav#options

**Comment by Swebmaster** [comment]
It works great! 
I didn't know I needed to download the plugin. 
Thank you!
