### ISSUE TITLE
Add active class to main menu button

### ISSUE THREAD

**Issue by AlphaBlossom** [mrjasonweaver/flexnav#67]
Hello, 

Thanks for the great work with this! I have a feature request:

Please add an "active" class to the main menu button, so that you can style it differently when open vs. closed.

I see you've added it to the sub menus, but it would be great to be able to add it to the main nav bar as well.

Thank you!

**Comment by mrjasonweaver** [comment]
@AlphaBlossom This has been added in Flexnav v1.2.2

**Comment by juanfernandes** [comment]
I trying the latest version and I have this issue. 

Its not adding the class 'active' or any other class to the main menu li/href to reflect the page we are on. 

Do I need to add something to make this work? 

Wasn't sure if it was best to comment here or open a new one. 

Thanks in advance.

**Comment by mrjasonweaver** [comment]
@juanfernandes FlexNav doesn't add active/current classes to menu items.
