### ISSUE TITLE
Add 0 padding to ".flexnav" and ".flexnav li ul"

### ISSUE THREAD

**Issue by lmeurs** [mrjasonweaver/flexnav#68]
Menu items indent when _page.css_ is removed from the demo _index.html_ file. This is because _page.css_ resets padding to zero for many elements, including the `ul` element.

By setting the padding to zero in _flexnav.css_ for all the flexnav `ul`'s this problem is solved and FlexNav is (or seems) no longer depending on _page.css_.

**Comment by mrjasonweaver** [comment]
Sorry for the late reply. FlexNav is just the JavaScript plugin. The example css might have a few bugs or might not work for you in your specific project.
