### ISSUE TITLE
Sub Menu Hover FF only

### ISSUE THREAD

**Issue by Jon3** [mrjasonweaver/flexnav#69]
I have integrated the FlexNav Menu and would like to use it in a template, however sub menu items (level 3 & level 4) only work in FireFox. 
http://flexible.websitesolved.co.uk
If you view the above website in Chrome or IE, navigate to Computers > Desktops 
There are level 3 and level 4 categories that only appear in FireFox.
These categories are accesible on the smaller Menu but do not appear on the desktop sized menu.
It works perfectly in FireFox.
If you remove  .flexnav li ul li > ul {
      margin-left: 100%;
      top: 0; }
Firefox behaves in the same way as Chrome and IE.
I'm guessing I need to modify the css for Chrome and IE, but am not sure why this might be happening.

**Comment by bradweaver** [comment]
+1 having the same issue and wasn't having it before the last updates.

**Comment by mrjasonweaver** [comment]
Sorry for the late reply. FlexNav 3 and 4 levels are working fine in the demo here: http://jasonweaver.name/lab/flexiblenavigation/
