### ISSUE TITLE
Keep menu open on page refresh

### ISSUE THREAD

**Issue by niallthompson** [mrjasonweaver/flexnav#7]
How would I go about keeping the menu open when it is clicked and another page is loaded?

I presume this will create issues for the smallest breakpoint if there are many options in the dropdown...

Any thoughts?

**Comment by mrjasonweaver** [comment]
The menu isn't designed to work that way. You'd have to somehow match a body class with how you want the menu to display. So, for example, if you had a body class of "about" for a particular page, you'd need to write specific styles to have the menu open to your "about" navigation tab. Make sense?

**Comment by niallthompson** [comment]
brilliant, yep all makes sense. I'll have a play and see if it suits the project...

many thanks for the reply
