### ISSUE TITLE
After resizing in IE10, menu behavior is erratic

### ISSUE THREAD

**Issue by dan121** [mrjasonweaver/flexnav#72]
After resizing the browser window in IE10, the drop down menus become unusable. The issue only resolves itself after refreshing the browser.

**Comment by danny-englander** [comment]
I've experienced a similar thing with version 1.1 in Chrome. If I go back to v. 0.8, this does not happen. The menu state seems to become confused somehow.

**Comment by mrjasonweaver** [comment]
This is a known bug. https://github.com/indyplanets/flexnav/issues/62 Closing as duplicate.
