### ISSUE TITLE
Submenu keep open without mouse hover, it doesn't close or hide

### ISSUE THREAD

**Issue by didietc** [mrjasonweaver/flexnav#74]
Hi This is very cool navigation indeed but i experience something i'm not sure if it's a bug, but i got this issue.
I don't know why the submenu doesn't want to close, just stays open. but this is only happen on the landing page http://speechacademyasia.com/. but it works fine on the other page http://speechacademyasia.com/gallery/.

And also in the lower screen size of 800px, the icon "touch button" is missing. same case as above only happen on landing page.

I do really appreciate if anybody able to help me.
Thank you

**Comment by mrjasonweaver** [comment]
Sorry for the late reply. Hope you found a solution.
