### ISSUE TITLE
Doesn't Work on the iPhone

### ISSUE THREAD

**Issue by june-zz** [mrjasonweaver/flexnav#75]
This is possibly an issue with my implementation but I wasn't sure where else to submit a support question. In short, this works great when tested on a desktop, including at smaller responsive browser sizes. I then tested this in both Xcode's device simulator and on my iphone and the menu doesn't open at all. When you tap the menu button the hover/active state flashes but quickly goes away and no menu appears.

Some notes about my implementation:
1. I'm using a different class for the menu list but updated the js snippet you add to your page to reflect this.
2. I've added some extra javascript that replaces the triangle with a + or - depending on the state of a submenu.
3. The js snippet I'm using to initialize the code and create the +/- effect:
'''     <script type="text/javascript">
    
    </script>'''
4. I added the menu-button class to an existing menu toggle button. There doesn't seem to be any issue with this until I get to the iphone level. This site is built within wordpress so I just used the menu button that was already in place. I quickly created a fake menu button that only has the menu-button class and still the same issue. It will open the menu on a desktop but not on an iphone.

Any help would be greatly appreciated!

Thanks!

June

**Comment by june-zz** [comment]
It looks like my js snippet didn't go through. Trying again:
`<script type="text/javascript">
    
    </script>`

**Comment by june-zz** [comment]
To follow up, I think I may have resolved the issue but now need to restyle everything. The button works at both the desktop and iphone level now but the iphone menu is partially styled and the desktop level has no styling. 

I replaced my nav-menu class (in the js snippet, style sheet and menu class attribute) with flexnav. The nav-menu class is a default wordpress class so I'm guessing there was other navigation javascript conflicting with the flexnav. 

Thanks for the plugin!

**Comment by mrjasonweaver** [comment]
Sorry for the late reply!  Glad you got a fix for it.
