### ISSUE TITLE
Infinite Flickering...

### ISSUE THREAD

**Issue by robr24** [mrjasonweaver/flexnav#76]
If I move quickly up and down over a nav menu item and land on the submenu about 1/2 way down, I can trigger an infinite flickering of the menu, fyi...

**Comment by mrjasonweaver** [comment]
Sorry for the late reply. You can use the HoverIntent plugin with FlexNav and set up options:

```
'hoverIntent': false, // Change to true for use with hoverIntent plugin
'hoverIntentTimeout': 150 // hoverIntent default timeout        

```
