### ISSUE TITLE
iPad sub menu links break menu

### ISSUE THREAD

**Issue by RhysyG** [mrjasonweaver/flexnav#77]
Hey Guys,

Great menu, love it. Works on every device except for my iPad.

All the menu items work in the demo except "Item 2" which contains the multi level navigation. When I click to expand using the "Tap Arrow", then try to click a sub menu link (not sub menu tap arrows) the menu just disappears, then "Item 2" menu won't expand anymore and I have to refresh the page to reset it.

Step by step:

Click item 2 "tap arrow"
Click on a sub menu item that has another sub menu (ie Sub 1 Item 2)
Menu Disapears and breaks.

Have you come across this problem?

Thanks,
Rhys.

**Comment by mrjasonweaver** [comment]
Can't reproduce.

**Comment by RhysyG** [comment]
Hey Indyplanets,

Hmm that's strange. Still happens for me.

Here's a video of the problem.

https://www.dropbox.com/s/5gyvqtztomrdtp7/FlexNav_iPad_Problem.MOV

Thanks,
Rhys.

**Comment by mrjasonweaver** [comment]
@RhysyG I can't reproduce on iOS 7 - Also, tapping a submenu item link would go to another page and reload the menu in a real world situation.

**Comment by RhysyG** [comment]
Hey,

Yeah could be just an IOS 6 thing.

I'm not sure if you have done anything to the code, but it now works perfectly fine and doesn't break like in the example video above.

Thanks you very much if you fixed the code!

Cheers,
Rhys.

**Comment by mrjasonweaver** [comment]
@RhysyG Yeah, I pushed an update ;) https://github.com/indyplanets/flexnav/releases/tag/v1.2
