### ISSUE TITLE
IE9 bug - ul submenu slide up when you hover and slide down when you out

### ISSUE THREAD

**Issue by flodar** [mrjasonweaver/flexnav#79]
![ie9_bug](https://f.cloud.github.com/assets/859725/1212317/50df4be0-2616-11e3-9bde-bf3acab76f83.jpg)

**Comment by flodar** [comment]
In IE8 works perfect...

**Comment by mrjasonweaver** [comment]
Can't seem to replicate this. FlexNav is really the JavaScript plugin— the example css may have some bugs. Closing.

**Comment by chrisdivyak** [comment]
I was able to fix this in IE9 by using the hoverIntent plugin. http://cherne.net/brian/resources/jquery.hoverIntent.html

Then just append your flexnav call.

$(".flexnav").flexNav({
        'hoverIntent': true // Change to true for use with hoverIntent plugin
    });

**Comment by irmela** [comment]
Had the same problem. 
hoverIntent works for me as well. @chrisdivyak THANKS!

**Comment by Skerins** [comment]
Verified.  Worked for me as well.
