### ISSUE TITLE
allow for use of more than 1 flexnav menu

### ISSUE THREAD

**Issue by anointed** [mrjasonweaver/flexnav#8]
I tried adding 2 separate 'flexnav' menu's to my template and found that it causes problems with the drop down logic. Basically if I click the down arrow on one menu, both menu's expand/collapse.

**Comment by mrjasonweaver** [comment]
You'd have to make 2 separate id's for each I'm assuming instead of `[role='navigation']`. Tried that?

Do you have your code somewhere so I can take a look?

**Comment by ghost** [comment]
You do indeed need 2 separate id's... but both menus will still respond to a men-button click. 

I changed this:

<pre lang="javascript"><code>
// Toggle for nav menu
$('.menu-button').click(function() {
    $this.slideToggle(settings.animationSpeed); 
});
</code></pre>


to this:

<pre lang="javascript"><code>
// Use unbind to prevent the click from firing twice...
// There's probably a better way to fix that...
$('.menu-button').unbind('click').click(function() {
    // Get the .menu-button that was clicked and animate
    // the relevant menu
    $(this).next().slideToggle(settings.animationSpeed);    
});
</code></pre>


and it worked for my purposes...

**Comment by mrjasonweaver** [comment]
@wmetz Nice! Thanks for sharing.

**Comment by mrjasonweaver** [comment]
This plugin is ideally for a global navigation. Closing this issue.

**Comment by ghost** [comment]
@wmetz I tried your approach and it broke both menu buttons. I changed the role and add the new role to the script at the bottom of the page and changed the JQuery to have your code you provide. Any suggestions of where I went wrong?
