### ISSUE TITLE
Submenu starts flickering on fade in when moving the mouse to a submenu item

### ISSUE THREAD

**Issue by lmeurs** [mrjasonweaver/flexnav#82]
I tested this at http://jasonweaver.name/lab/flexiblenavigation/ with the latest Chrome and Firefox on Windows 7.

When the menu is in desktop mode and fully collapsed, I move the mouse from above any menu item downwards so it's submenu appears. I keep moving the mouse to one of it's submenu items and then the submenu starts flickering cq. appearing / disappearing.

**Comment by mrjasonweaver** [comment]
@lmeurs See https://github.com/indyplanets/flexnav/issues/76

**Comment by pinkaycutie** [comment]
yes I have the same problem too. please help! :) Thanks!
