### ISSUE TITLE
Jumbled menu when hovering in ie9

### ISSUE THREAD

**Issue by gscap101** [mrjasonweaver/flexnav#84]
When hovering over a menu that has a sub menu sometimes the sub menu shows itself jumbled together when hovering out of the menu. as seen in the included screenshot.  This only occurs in ie9 for me.

http://imgur.com/PwlomGR

**Comment by mrjasonweaver** [comment]
Hmm, can't replicate this at http://jasonweaver.name/lab/flexiblenavigation/

**Comment by gscap101** [comment]
I apologize, I should have given more information.  

Here is my implementation.  Works fine in other browsers but not ie9.  You can see it here : 

http://www.vulcaninc.com/?p=vulcan_inc_mythology_V4

Also, here is an mp4 of what I am seeing.

http://www.vulcaninc.com/temp/flexnav.mp4
