### ISSUE TITLE
Jumbled menu

### ISSUE THREAD

**Issue by gscap101** [mrjasonweaver/flexnav#86]
When hovering over a menu that has a sub menu sometimes the sub menu shows itself jumbled together when hovering out of the menu. as seen in the included screenshot. This only occurs in ie9 for me.

http://imgur.com/PwlomGR 

Here is my implementation. Works fine in other browsers but not ie9. You can see it here :

http://www.vulcaninc.com/?p=vulcan_inc_mythology_V4

Also, here is an mp4 of what I am seeing.

http://www.vulcaninc.com/temp/flexnav.mp4

**Comment by mrjasonweaver** [comment]
Can't reproduce at http://jasonweaver.name/lab/flexiblenavigation/ in ie9.
