### ISSUE TITLE
Have you tried this within a Bootstrap 3 layout? It sseems the drop-down animation suffers from flickering on "desktop" mode and the ul.show sub menus are misaligned. Any suggestions?  

### ISSUE THREAD

**Issue by PeterKnightDigital** [mrjasonweaver/flexnav#87]

**Comment by mrjasonweaver** [comment]
Sorry, haven't tried with bootstrap. Maybe try looking into this solution for the flickering: http://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform
