### ISSUE TITLE
remove media query from flexnav.css (rewrite to use classes instead)

### ISSUE THREAD

**Issue by jenlampton** [mrjasonweaver/flexnav#90]
Hello :) I'm working on a Drupal module that integrates this awesome jQuery plugin as an external library.  https://drupal.org/project/flexnav

Unfortunately, if someone wants to change their breakpoint from 800px to say, 900px, not only does the data-attribute on the UL tag need to be changed, but the CSS file will need to be modified directly in order for the menu to behave correctly.

If, instead, a CSS class were added by jQuery and the accompanying stylesheet were written to use this class, then this plugin wouldn't need to be hacked every time the breakpoint needed to be changed.

I know this may mean adding another div to what's otherwise very elegant HTML, but I think it may be worth it in the name of re-use! :)

Thanks for all your work on this, really neat stuff!

**Comment by mrjasonweaver** [comment]
@jenlampton Cool. I'll see what I can do.

**Comment by mrjasonweaver** [comment]
@jenlampton Actually, Flexnav already adds classes based on screen size. `.lg-screen` > breakpoint and `sm-screen` < breakpoint. Wouldn't be hard to change the css to accommodate your request. I'd rather not change the core css though as this request is certainly an edge case.

**Comment by ghost** [comment]
I'm with Jen on this one and I don't think it's an edge case. This library would be a lot more flexible if the markup wasn't in charge of where the breakpoint should be.

Top work on this BTW. Been doing a fair bit of research into RWD menu libraries recently and keep coming back to this one as my possible go-to.

**Comment by areatype** [comment]
I agree that it's not an edge case. Different site require different breakpoints.

**Comment by jenlampton** [comment]
It doesn't look like there's a way for us to re-open the issue.  Should we create a new one to get it back on @indyplanets radar? Not sure about etiquette here.
