### ISSUE TITLE
auto-determine width based on number of nav items

### ISSUE THREAD

**Issue by jenlampton** [mrjasonweaver/flexnav#91]
It appears as though we are only allowed 5 navigation items, since the width is hard-coded to 20%. 

It would be wonderful if there was a way to count the number of items in the menu, and determine the width automatically with javascript.

**Comment by mrjasonweaver** [comment]
Hi @jenlampton - I've added this in v 1.2.1 (https://github.com/indyplanets/flexnav/commit/44bb776220f0d19145449871aeb439c5e9fab449). Thanks!

**Comment by mrjasonweaver** [comment]
@jenlampton Here's the latest release - https://github.com/indyplanets/flexnav/releases/tag/v1.2.2

**Comment by Helrunar** [comment]
I think, it's a better solutions to set the width with CSS and not a calculated width as inline style. If we have i.e. short and long Menu-items we can work with padding and it will looks better.

**Comment by eduski** [comment]
I agree with Helrunar, is it possible to not make each li an equal width within the menu?  Thanks, this is a great menu.

**Comment by mrjasonweaver** [comment]
@jenlampton @Helrunar @eduski I've made an option for calculating menu items that defaults to false.

```
<script>
  $(".flexnav").flexNav({
    'calcItemWidths': true // dynamically calcs top level nav item widths
  });
</script>

```

https://github.com/indyplanets/flexnav/releases/tag/v1.2.3
