### ISSUE TITLE
IE9 Compatibility View Sub-menu issue

### ISSUE THREAD

**Issue by reemaarke** [mrjasonweaver/flexnav#93]
Hi,

Firstly, thank you for creating this amazing code. It works great in all the browsers except for in IE9 Compatibility mode. The sub-menu shows up jumbled when you hover on the main menu items or sub-items with more than one column of sub-menu showing up. Do you know what might be causing this?

Thanks,
Reema.

**Comment by mrjasonweaver** [comment]
Hi @reemaarke, This plugin's default css doesn't support IE9 compatibility mode. The css is meant as an example and to be edited to make your own. Think of it as a starting point for your project.
