### ISSUE TITLE
IE9 Compatibility View - Submenu issue

### ISSUE THREAD

**Issue by reemaarke** [mrjasonweaver/flexnav#94]
Hi,

Firstly, thank you for creating this amazing code. It works great in all the browsers except for in IE9 Compatibility mode. The sub-menu shows up jumbled when you hover on the main menu items or sub-items with more than one column of sub-menu showing up. Do you know what might be causing this?

Thanks,
Reema.

**Comment by mrjasonweaver** [comment]
Closing as duplicate: https://github.com/indyplanets/flexnav/issues/93
