### ISSUE TITLE
Errors in chrome console

### ISSUE THREAD

**Issue by coreycondardo** [mrjasonweaver/flexnav#95]
Love the menu! Sadly I can't get it to work. 

Once I get it all configured I get this on line 106:
    $(toggle_selector).on('click', function(e) {
Uncaught TypeError: Object # <Object> has no method 'on'

**Comment by mrjasonweaver** [comment]
@ccondardo That error makes me think you don't have jQuery called before the init.

**Comment by coreycondardo** [comment]
I _might_ be a moron, but to test I added this code RIGHT before where I put $(".flexnav").flexNav();

if (typeof jQuery != 'undefined') {
alert("jQuery library is loaded!");
 }else{
alert("jQuery library is not found!");
}

The alert did work, which I think proves jQuery is loaded?

I'm using Drupal, so there might be something going on there. Is there a more efficient test I can perform to see if your hypothesis is correct? Is this a valid test to see if jQuery is called before the init (not full sure what that means).

Appreciate the help!

**Comment by edweezy** [comment]
```
                                                                                                                                 @ccondardo try using jQuery instead of the $? Not sure if that'll help.                                                                                                                                                                                                                                                                                                                                                                             From: ccondardoSent: Tuesday, November 19, 2013 8:43 PMTo: indyplanets/flexnavReply To: indyplanets/flexnavSubject: Re: [flexnav] Errors in chrome console (#95)I might be a moron, but to test I added this code RIGHT before where I put $(".flexnav").flexNav();
```

if (typeof jQuery != 'undefined') {
alert("jQuery library is loaded!");
 }else{
alert("jQuery library is not found!");
}

The alert did work, which I think proves jQuery is loaded?

I'm using Drupal, so there might be something going on there. Is there a more efficient test I can perform to see if your hypothesis is correct? Is this a valid test to see if jQuery is called before the init (not full sure what that means).

Appreciate the help!

—Reply to this email directly or view it on GitHub.

**Comment by mrjasonweaver** [comment]
@ccondardo Also make sure you are using jQuery 1.7+

**Comment by ghost** [comment]
Hi, I work with @ccondardo , and we are much closer.  

The "show" class gets attached to the parent <ul> tag, but the sub menus don't show up when you are under the breakpoint.

You can see the site here: http://vtc.gravityswitch.com/

I've trie stripping out all of the other styling, but that didn't help. . . Does it matter that we are using jQuery 1.10?

Thanks!

**Comment by mrjasonweaver** [comment]
@rarcher @ccondardo 

jQuery 1.10 is fine. Anything over jQuery 1.7 works. Make sure you don't have flexnav styles overwritten. [Here's a post](http://highrockmedia.com/blog/theming-multi-level-responsive-menu-drupal-7) from a Drupal developer using FlexNav. Might want to ping him to see if he has any insights. Sorry I don't use Drupal.

Closing this ticket as it's beyond scope of FlexNav code.

**Comment by coreycondardo** [comment]
Thanks for the help, you're awesome.
