### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tolgafiratoglu** [mrjasonweaver/flexnav#97]
Hello,
What's the license of the script? This is important, I think you should include a license file to the repo.

**Comment by mrjasonweaver** [comment]
FlexNav is free and unencumbered software released into the public domain. This is documented at the top of the [jquery.flexnav.js script](https://github.com/indyplanets/flexnav/blob/master/js/jquery.flexnav.js). 

Also just added a LICENSE file.
