### ISSUE TITLE
Bootstrap 3 incompatibility

### ISSUE THREAD

**Issue by cr4ckm3** [mrjasonweaver/flexnav#98]
Bootstrap 3 also use 'show' class with display: block !important; and it causes issue with dropdown. I suggest to just add some prefix to this class. Probably same issue will be with B2 but I didn't test it.

**Comment by ccarrascom** [comment]
you are right, i run into the same issue

**Comment by mrjasonweaver** [comment]
@cr4ckm3 I've prefixed 'show' classes with `flexnav-`. Thanks! https://github.com/indyplanets/flexnav/releases/tag/v1.3

**Comment by osc2nuke** [comment]
I tested this with bootstrap 3.X , however i not get the "nice layout" as expected when using the standard css file coming with flexnav.
May i ask how you made it bootstrap compatible?
